### ISSUE TITLE
Design layout web

### ISSUE THREAD

**Issue by khoavpt** [hieuhn09/IELTS-Writing-Checker#7]

**Comment by Duonn512** [comment]
Ở trạng thái chưa signed-in ấn vào nút sign-in sẽ tự động điều hướng về homepage và hiện 1 box sign-in/ register
Ở trạng thái signed-in ấn vào sign out sẽ hiện check box hỏi có muốn sign-out không trước, nếu chọn có thì điều hướng về homepage và đăng xuất
